PL_Kranon/Controllers/LibroController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL_Kranon.Controllers
{
    public class LibroController : Controller
    {

        [HttpGet]
        public IActionResult GetAll()
         {
            ML.Libro libro = new ML.Libro();
            ML.Autor autor = new ML.Autor();
            ML.Editorial editorial = new ML.Editorial();
            libro.Libros = new List<object>();
            autor.Autores = new List<object>();
            editorial.Editoriales = new List<object>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:5235/api/");

                var responseTask = client.GetAsync("Autor/GetAll");
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {

                        ML.Autor resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Autor>(resultItem.ToString());
                        autor.Autores.Add(resultItemList);
                    }
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al hacer la consulta";
                    return View("Modal");
                }

            }
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:5235/api/");

                var responseTask = client.GetAsync("Editorial/GetAll");
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {

                        ML.Editorial resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Editorial>(resultItem.ToString());
                        editorial.Editoriales.Add(resultItemList);
                    }
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al hacer la consulta";
                    return View("Modal");
                }

            }
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:5235/api/");

                 var responseTask = client.GetAsync("Libro/GetAll");
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
    
                        ML.Libro resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Libro>(resultItem.ToString());
                        libro.Libros.Add(resultItemList);
                    }
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al hacer la consulta";
                    return View("Modal");
                }
                libro.Autor = new ML.Autor();
                libro.Autor.Autores = autor.Autores;
                libro.Editorial = new ML.Editorial();
                libro.Editorial.Editoriales = editorial.Editoriales;
            }
            return View(libro);
        }

        [HttpPost]
        public IActionResult GetAll(ML.Libro libro)
        {
            
            ML.Autor autor = new ML.Autor();
            ML.Editorial editorial = new ML.Editorial();
            libro.Libros = new List<object>();
            autor.Autores = new List<object>();
            editorial.Editoriales = new List<object>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:5235/api/");

                var responseTask = client.GetAsync("Autor/GetAll");
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {

                        ML.Autor resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Autor>(resultItem.ToString());
                        autor.Autores.Add(resultItemList);
                    }
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al hacer la consulta";
                    return View("Modal");
                }

            }
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:5235/api/");

                var responseTask = client.GetAsync("Editorial/GetAll");
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {

                        ML.Editorial resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Editorial>(resultItem.ToString());
                        editorial.Editoriales.Add(resultItemList);
                    }
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al hacer la consulta";
                    return View("Modal");
                }

            }
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:5235/api/");

                var responseTask = client.PostAsJsonAsync("Libro/GetAll", libro);
                responseTask.Wait();

                var resultUsuario = responseTask.Result;

                if (resultUsuario.IsSuccessStatusCode)
                {
                    var readTask = resultUsuario.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
                        ML.Libro resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Libro>(resultItem.ToString());
                        libro.Libros.Add(resultItemList);
                    }
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al hacer la consulta";
                    return View("Modal");
                }
                libro.Autor = new ML.Autor();
                libro.Autor.Autores = autor.Autores;
                libro.Editorial = new ML.Editorial();
                libro.Editorial.Editoriales = editorial.Editoriales;
            }
            return View(libro);
        }

        [HttpGet]
        public ActionResult Delete(int idLibro)
        {
            ML.Result resultListProduct = new ML.Result();
          
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:5235/api/");


                var postTask = client.GetAsync("Libro/Delete/" + idLibro);
                postTask.Wait();

                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    ViewBag.Message = "Se Elimino con exito";
                    return View("Modal");
                    ;
                }
                else
                {
                    ViewBag.Message = "Error al eliminar";
                    return View("Modal");
                }
            }
        }








        [HttpGet]
        public ActionResult Form(int? idLibro)
        {
            ML.Libro libro = new ML.Libro();
            ML.Autor autor = new ML.Autor();
            ML.Editorial editorial = new ML.Editorial();
            libro.Libros = new List<object>();
            autor.Autores = new List<object>();
            libro.Editorial = new ML.Editorial();
            editorial.Editoriales = new List<object>();
            libro.Autor = new ML.Autor();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:5235/api/");

                var responseTask = client.GetAsync("Autor/GetAll");
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {

                        ML.Autor resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Autor>(resultItem.ToString());
                        autor.Autores.Add(resultItemList);
                    }
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al hacer la consulta";
                    return View("Modal");
                }

            }
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:5235/api/");

                var responseTask = client.GetAsync("Editorial/GetAll");
                responseTask.Wait();

PL_Kranon/Views/Libro/Form.cshtml
@model ML.Libro
@{
    ViewData["Title"] = "Form";
}

<h2>Formulario</h2>

<div class="row">

    <div class="col-md-12">

        @using (Html.BeginForm("Form", "Libro", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            <div class="row">
                <div class="col" style="display:none">
                    @Html.LabelFor(model => model.IdLibro, new { @class = "visually-hidden" })

                    @Html.TextBoxFor(model => model.IdLibro, new { @class = "visually-hidden form-control" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Titulo)

                    @Html.TextBoxFor(model => model.Titulo, new { @class = "form-control", @id = "txtNombre" })
                </div>
              
                <div class="col-md-3">
                    @Html.LabelFor(model => model.AñoPublicacion)

                    @Html.TextBoxFor(model => model.AñoPublicacion, new { @class = "form-control", @id = "txtNombre" })
                </div>

                <div class="col-md-3">
                    @Html.LabelFor(model => model.Autor)
                    @Html.DropDownListFor(model => model.Autor.IdAutor, new SelectList(Model.Autor.Autores, "IdAutor", "NombreCompleto"), "Selecciona una opción", new { @class = "form-control" })

                   
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Editorial)
                    @Html.DropDownListFor(model => model.Editorial.IdEditorial, new SelectList(Model.Editorial.Editoriales, "IdEditorial", "Nombre"), "Selecciona una opción", new { @class = "form-control" })

                </div>
                </div>

                <div class="row">
                      <div class="col-md-6">
                    @Html.LabelFor(model => model.Portada)
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user-plus"></i></span>
                        <input id="inpImagen" type='file' class="form-control" name="inpImagen" onchange="validateFile(this), visualizarImagen(this);  " />
                    </div>
                    @if (Model.Portada == null)
                    {
                        <img id="Img" src="/Images/guest-user.png" style="width:250px ; height:250px" />
                    }
                    else
                    {
                        <img id="Img" src="data:image/*;base64,@Model.Portada" style="width:250px ; height:250px" />
                    }
                </div>

                </div>
              
                  <div class="col-md-12">
                    @Html.LabelFor(model => model.Sinopsis)

                    @Html.TextAreaFor(model => model.Sinopsis, new { @class = "form-control", @id = "txtNombre" })
                </div>
            
            <br />
            <br />
            <div class="row">
                <div class="col">
                    <input type="submit" value="Guardar" class="btn btn-success" />

                    @Html.ActionLink("Regresar", "GetAll", "Aseguradora", htmlAttributes: new { @class = "btn btn-danger" })
                </div>

            </div>


        }

    </div>

</div>





    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script type="text/javascript">

    function validateFile() {
        var allowedExtension = ['jpeg', 'jpg', 'png'];
        var fileExtension = document.getElementById('inpImagen').value.split('.').pop().toLowerCase();
        var isValidFile = false;
        for (var index in allowedExtension) {
            if (fileExtension === allowedExtension[index]) {
                isValidFile = true;
                break;
            }
        }
        if (!isValidFile) {
            alert('Las extensiones permitidas son : *.' + allowedExtension.join(', *.'));
            document.getElementById('inpImagen').value = ""
        }
        return isValidFile;
    }
    function visualizarImagen(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#Img').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }

    

PL_Kranon/Views/Libro/GetAll.cshtml
@model ML.Libro
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class=row>
        <div class="text-center">
            <h2>Libros</h2>

        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h5>Seleccione una Libro para editarlo o + para agregar...</h5>
            <hr />
        </div>
    </div>

</div>
<div class="row">

    <div class="col-md-12">
        @using (Html.BeginForm("GetAll", "Libro", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="container">
                <div style="float:right;">
                    @Html.ActionLink("Agregar", "Form", "Libro", htmlAttributes: new { @class = "btn btn-success bi bi-person-plus-fill" })
                </div>
            </div>

            <div class="row">

                <div class="col-md-3">
                    @Html.LabelFor(model => model.Titulo)
                    <div class="input-group">
                        <span class="input-group-text">
                            <i class="fa-solid fa-circle-user"></i>
                        </span>
                        
                        @Html.TextBoxFor(model => model.Titulo, new { @class = "form-control", @id = "txtNombre",@placeholder = "Titulo del libro"})

                    
                  

                    </div>
                </div>

                <div class="col-md-3">
                    @Html.LabelFor(model => model.AñoPublicacion)
                    <div class="input-group">
                        <span class="input-group-text"><i class="fa-solid fa-circle-user"></i></span>
                        @Html.TextBoxFor(model => model.AñoPublicacion, new { @class = "form-control", @id = "publicacion" })

                        
                    </div>
                </div>

                <div class="col-md-3">
                    @Html.LabelFor(model => model.Autor)


                    @Html.DropDownListFor(model => model.Autor.IdAutor, new SelectList(Model.Autor.Autores, "IdAutor", "NombreCompleto"), "Selecciona una opción", new { @class = "form-control" })


                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Editorial)


                    @Html.DropDownListFor(model => model.Editorial.IdEditorial, new SelectList(Model.Editorial.Editoriales, "IdEditorial", "Nombre"), "Selecciona una opción", new { @class = "form-control" })

                 

                </div>
            </div>
            <br />
            <div class="container">

                <div class="col">
                    <input type="submit" value="Buscar" class="btn btn-info" />

                </div>
            </div>
        }
    </div>
</div>
<br />

<table class="table   table-hover table-bordered table-responsive">
    <tbody>
        @foreach (ML.Libro libro in Model.Libros)
        {
            
        <td style="display :none;">@libro.IdLibro </td>

        <div class="col row-cols-2 row-cols-md-3 g-4" style="display: inline-block; text-align-center">

            <div class="card card border-dark mb-4 border-2 row" style="width: 22rem;">
                    @if (libro.Portada == null)
                    {
                    <img src="/Images/guest-user.png" width=250px height=250px />

                    }
                    else
                    {
                    <img id="Img" src="data:image/*;base64,@libro.Portada" style="width:250px ; height:250px" />
                    }
                <div class="card-body; card-img-top;" style="width: 300px; height: 700px;">
                    <h5 class="card-title card-header text-center bg-secondary" >@libro.Titulo</h5>
                    <p class="card-text" >@libro.Autor.Nombre @libro.Autor.ApellidoPaterno @libro.Autor.ApellidoMaterno </p>
                    <p class="card-text">@libro.Editorial.Nombre </p>
                    <p class="card-text">@libro.AñoPublicacion</p>

                    <p class="card-text">@libro.Sinopsis</p>

                    <a class="btn btn-warning"
                   href="@Url.Action("Form", "Libro", new {IdLibro=libro.IdLibro})">Actualizar
                        <i class="bi bi-pencil-square"></i>
                    </a>
                    <a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete","Libro",new {idLibro=libro.IdLibro})"
                   onclick="return confirm('Estas seguro de que deseas eliminar el Libro? ');">Eliminar</a>
                </div>

            </div>
        </div>

        }

    </tbody>
</table>

PL_Kranon/Views/Libro/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Libro", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>